# Generated by Django 6.0.3 on 2026-05-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_padre_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculopadrehijo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
