# Generated by Django 4.2.29 on 2026-03-08 17:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('negativo_consecutivo', '⚠️ Emocion negativa varios dias'), ('cambio_brusco', '📉 Cambio emocional brusco'), ('puntaje_bajo', '🔴 Puntaje muy bajo')], max_length=30)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media')], default='media', max_length=10)),
                ('mensaje', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('nota_resolucion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('emocion', models.CharField(choices=[('feliz', '😊 Feliz'), ('tranquilo', '😌 Tranquilo'), ('estresado', '😰 Estresado'), ('triste', '😢 Triste'), ('enojado', '😠 Enojado')], max_length=20)),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Escala emocional (1-5)')),
                ('comentario', models.TextField(blank=True, verbose_name='¿Como te sientes? (opcional)')),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_emocionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Emocional',
                'verbose_name_plural': 'Registros Emocionales',
                'ordering': ['-fecha', '-hora_registro'],
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
