# Generated by Django 4.2.30 on 2026-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0008_encuestas_retos_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='emocion_del_dia',
            field=models.CharField(blank=True, choices=[('feliz', '😊 Feliz'), ('tranquilo', '😌 Tranquilo'), ('estresado', '😰 Estresado'), ('triste', '😢 Triste'), ('enojado', '😠 Enojado')], max_length=20, verbose_name='Como me siento al escribir esto'),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='estado',
            field=models.CharField(choices=[('borrador', '📝 Borrador'), ('guardado', '💾 Guardado')], default='guardado', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensajedirecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postforo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retogrupal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rutinacierre',
            name='fue_dificil',
            field=models.TextField(blank=True, verbose_name='Que fue dificil'),
        ),
        migrations.AlterField(
            model_name='rutinacierre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rutinacierre',
            name='manana',
            field=models.TextField(blank=True, verbose_name='Que necesito manana'),
        ),
    ]
