# Generated by Django 6.0.3 on 2026-05-08 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0011_citacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaprofesor',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Nota del Profesor', 'verbose_name_plural': 'Notas del Profesor'},
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('negativo_consecutivo', 'Emocion negativa varios dias'), ('cambio_brusco', 'Cambio emocional brusco'), ('puntaje_bajo', 'Puntaje muy bajo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='citaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='emocion_del_dia',
            field=models.CharField(blank=True, choices=[('feliz', 'Feliz'), ('tranquilo', 'Tranquilo'), ('estresado', 'Estresado'), ('triste', 'Triste'), ('enojado', 'Enojado')], max_length=20, verbose_name='Como me siento al escribir esto'),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('guardado', 'Guardado')], default='guardado', max_length=10),
        ),
        migrations.AlterField(
            model_name='notaprofesor',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='notas_escritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('logro', 'Logro desbloqueado'), ('mensaje', 'Nuevo mensaje'), ('encuesta', 'Encuesta pendiente'), ('reto', 'Nuevo reto'), ('alerta', 'Alerta emocional'), ('sistema', 'Sistema'), ('citacion', 'Citación')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registroemocional',
            name='emocion',
            field=models.CharField(choices=[('feliz', 'Feliz'), ('tranquilo', 'Tranquilo'), ('estresado', 'Estresado'), ('triste', 'Triste'), ('enojado', 'Enojado')], max_length=20),
        ),
    ]
