# Generated by Django 4.2.30 on 2026-05-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0013_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alerta',
            name='alerta_est_resuelta_idx',
        ),
        migrations.RemoveIndex(
            model_name='alerta',
            name='alerta_resol_prior_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensajedirecto',
            name='msg_dest_leido_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensajedirecto',
            name='msg_rem_dest_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroemocional',
            name='reg_fecha_estudiante_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroemocional',
            name='reg_estudiante_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroemocional',
            name='reg_estudiante_puntaje_idx',
        ),
    ]
