# Generated by Django 4.2.30 on 2026-06-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0016_notificacion_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='lugar',
            field=models.CharField(choices=[('psicologia', 'Oficina de Psicología'), ('coordinacion', 'Coordinación'), ('salon', 'Salón del profesor'), ('otro', 'Otro lugar')], default='psicologia', max_length=20),
        ),
    ]
