# Generated by Django 4.2.29 on 2026-03-08 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('respiracion', '🌬️ Ejercicio de Respiracion'), ('reflexion', '💭 Reflexion'), ('bienestar', '💚 Pregunta de Bienestar'), ('meditacion', '🧘 Meditacion'), ('gratitud', '🙏 Gratitud')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripcion / Instrucciones')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha limite (opcional)')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='activities.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de Actividad',
                'verbose_name_plural': 'Respuestas de Actividades',
                'ordering': ['-created_at'],
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
