# Generated by Django 6.0.3 on 2026-05-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('respiracion', 'Ejercicio de Respiracion'), ('reflexion', 'Reflexion'), ('bienestar', 'Pregunta de Bienestar'), ('meditacion', 'Meditacion'), ('gratitud', 'Gratitud')], max_length=20),
        ),
    ]
