# Generated by Django 4.2.30 on 2026-06-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_actividad_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('respiracion', 'Ejercicio de Respiración'), ('reflexion', 'Reflexión'), ('bienestar', 'Pregunta de Bienestar'), ('meditacion', 'Meditación'), ('gratitud', 'Gratitud')], max_length=20),
        ),
    ]
